name: Nightly Integration Tests

on:
  schedule:
    - cron: '0 3 * * *' # every day at 03:00 UTC
  workflow_dispatch: {}

jobs:
  instrumentation-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Android SDK components
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          force-avd-creation: true
          emulator-options: '-no-window -no-audio -no-boot-anim'
          script: |
            echo "Starting instrumentation tests"
            ./gradlew connectedDebugAndroidTest --no-daemon --stacktrace

      - name: Collect instrumentation test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-instrumentation-reports
          path: |
            app/build/outputs/androidTest-results/**
            app/build/reports/androidTests/**
            app/build/outputs/apk/**

      - name: Print emulator logs
        if: always()
        run: |
          echo "Collecting emulator logs (logcat)"
          adb logcat -d > emulator-logcat.txt || true
        continue-on-error: true

      - name: Upload emulator logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: emulator-logs
          path: emulator-logcat.txt

# Notes:
# - This workflow boots an Android emulator (API 30, Google APIs) and runs instrumentation tests.
# - It uses `reactivecircus/android-emulator-runner` which handles emulator setup and ADB.
# - Artifact upload paths include common report locations; adjust if your module structure differs.